### ISSUE TITLE
Test reader-graphml <default> element in GraphML

### ISSUE THREAD

**Issue by xamde** [Calpano/graphinout#71]
- [x] Create a synthetic graphml test file and verify that the XML content ends up in resulting GraphML (mock GioWriter)

e.g.

    <node> <data> <b>Hello</b>World </data></node>

- [ ] in key.default -> XML content works, default element content is really used as default value for nodes/edges/... where defined

**Comment by rasBab** [comment]
SAX does not understand HTML tags, and content containing HTML structures that do not comply with the XML standard will generate an error during initial rendering.

for example :  org.xml.sax.SAXParseException; lineNumber: 12; columnNumber: 11; The element type "link" must be terminated by the matching end-tag "</link>".

<graphml xmlns="http://graphml.graphdrawing.org/xmlns" >
<graph>
<node> <data> <html lang="en">
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="css/main.css">

        
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        
        </head>
    <body>
        <div class="ptext">
            <span class="border">
                <img src="./img/quote6-a.png" alt="Socrates Quote">
            </span>
        </div>
    </body></html></data></node>
</graph></graphml>

**Comment by xamde** [comment]
SAX Parser simply CANNOT deal with non-balanced tags at all. 
No feature to disable. Exception suppression also didnt work.

Ideas:
- We cannot parse GraphML with unbalanced tags inside data/default  --> cheap,. still solve most use cases
- We use a different XML parser, maybe StAX, ... --> maybe
- We use a pre-processor to escape all tags inside <data> / <default>  --> brittle

Whoever uses the valid GraphML file later, likely also has to deal with the same problems.
