### ISSUE TITLE
Add more tests: ValidatingGraphMlWriter test that errors are correctly reported

### ISSUE THREAD

**Issue by xamde** [Calpano/graphinout#81]
- [ ] check TODOs in code
- [ ] create 2-5 (max 10) synthetic test files [or JUnit tests directly, whichever is easier] to provoke the different validation errors

**Comment by rasBab** [comment]
For this test, it is not possible to use the file directly because this class takes the desired objects as input. For this reason, I wrote a parametric test for this class.
If we need to test the file, it is better to do it in the reader-graphml module.
